CREATE TABLE TBL_MEMBER(
	USERID			VARCHAR2(300) CONSTRAINT PK_USER PRIMARY KEY,
	USERPW			VARCHAR2(300),
	USERNAME		VARCHAR2(300),
	USERPHONE		VARCHAR2(300),
	USEREMAIL		VARCHAR2(300),
	USERPOSTCODE	VARCHAR2(300),
	USERADDR		VARCHAR2(300),
	USERCATEGORY	VARCHAR2(300),
	USERMANNER		VARCHAR2(300),
	USERBLOCKSTATE	VARCHAR2(300)
);
DROP TABLE TBL_MEMBER;

INSERT INTO TBL_MEMBER(USERID) VALUES('apple');
INSERT INTO TBL_MEMBER(USERID) VALUES('cherry');

SELECT * FROM TBL_MEMBER;
	
CREATE TABLE TBL_MAIL(
	MAILNUM			NUMBER(10),
	USERID			VARCHAR2(300),
	TARGETID		VARCHAR2(300),
	MAILCONTENT		VARCHAR2(2999),
	MAILDATE		DATE DEFAULT SYSDATE,
	READSTATE		CHAR(1) CONSTRAINT READ_CHECK CHECK(READSTATE = '0' OR READSTATE = '1'),
	IMPORTANT		CHAR(1) CONSTRAINT IM_CHECK CHECK(IMPORTANT = '0' OR IMPORTANT = '1'),
	DRAFT			CHAR(1) CONSTRAINT DRAFT_CHECK CHECK(DRAFT = '0' OR DRAFT = '1'),
	SENDER_DELETE	CHAR(1) CONSTRAINT SDEL_CHECK CHECK(SENDER_DELETE = '0' OR SENDER_DELETE = '1'),
	RECEIVER_DELETE	CHAR(1) CONSTRAINT RDEL_CHECK CHECK(RECEIVER_DELETE = '0' OR RECEIVER_DELETE = '1'),

	CONSTRAINT PK_MAIL PRIMARY KEY(MAILNUM),
	CONSTRAINT FK_MAIL FOREIGN KEY(USERID) REFERENCES TBL_MEMBER(USERID)
);

DROP TABLE TBL_MAIL;
DROP SEQUENCE MAIL_SEQ;

CREATE SEQUENCE MAIL_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1;

INSERT INTO TBL_MAIL (MAILNUM, USERID, TARGETID, MAILCONTENT, READSTATE, IMPORTANT, DRAFT, SENDER_DELETE, RECEIVER_DELETE)
VALUES(MAIL_SEQ.NEXTVAL, 'apple', 'cherry', '안녕', '0', '0', '0', '0', '0');
INSERT INTO TBL_MAIL (MAILNUM, USERID, TARGETID, MAILCONTENT, READSTATE, IMPORTANT, DRAFT, SENDER_DELETE, RECEIVER_DELETE)
VALUES(MAIL_SEQ.NEXTVAL, 'apple', 'cherry', '대답 좀 해주세요', '0', '0', '0', '0', '0');
INSERT INTO TBL_MAIL (MAILNUM, USERID, TARGETID, MAILCONTENT, READSTATE, IMPORTANT, DRAFT, SENDER_DELETE, RECEIVER_DELETE)
VALUES(MAIL_SEQ.NEXTVAL, 'apple', 'cherry', '여보세요', '0', '0', '0', '0', '0');
INSERT INTO TBL_MAIL (MAILNUM, USERID, TARGETID, MAILCONTENT, READSTATE, IMPORTANT, DRAFT, SENDER_DELETE, RECEIVER_DELETE)
VALUES(MAIL_SEQ.NEXTVAL, 'apple', 'cherry', '아직 상품 남아있나요ㅜㅜ', '0', '0', '0', '0', '0');
INSERT INTO TBL_MAIL (MAILNUM, USERID, TARGETID, MAILCONTENT, READSTATE, IMPORTANT, DRAFT, SENDER_DELETE, RECEIVER_DELETE)
VALUES(MAIL_SEQ.NEXTVAL, 'apple', 'cherry', '나 삭제할래요!', '0', '0', '0', '1', '0');
INSERT INTO TBL_MAIL (MAILNUM, USERID, TARGETID, MAILCONTENT, READSTATE, IMPORTANT, DRAFT, SENDER_DELETE, RECEIVER_DELETE)
VALUES(MAIL_SEQ.NEXTVAL, 'apple', 'cherry', '임시저장할꺼예요!!!', '0', '0', '1', '0', '0');
INSERT INTO TBL_MAIL (MAILNUM, USERID, TARGETID, MAILCONTENT, READSTATE, IMPORTANT, DRAFT, SENDER_DELETE, RECEIVER_DELETE)
VALUES(MAIL_SEQ.NEXTVAL, 'apple', 'cherry', '나 중요해 기억해줘', '0', '1', '0', '0', '0');
INSERT INTO TBL_MAIL (MAILNUM, USERID, TARGETID, MAILCONTENT, READSTATE, IMPORTANT, DRAFT, SENDER_DELETE, RECEIVER_DELETE)
VALUES(MAIL_SEQ.NEXTVAL, 'cherry', 'apple', 'DB 바꾸는중', '0', '0', '0', '0', '0');

--전체 쪽지함
SELECT * FROM TBL_MAIL;

--보낸 쪽지함
SELECT * FROM TBL_MAIL WHERE USERID = 'apple' AND SENDER_DELETE = '0' ORDER BY MAILNUM DESC;

--받은 쪽지함
SELECT * FROM TBL_MAIL WHERE TARGETID = 'apple' AND SENDER_DELETE = '0' ORDER BY MAILNUM DESC;

--임시저장
SELECT * FROM TBL_MAIL WHERE USERID = 'apple' AND DRAFT = '1' AND SENDER_DELETE = '0' ORDER BY MAILNUM DESC;

--중요저장
SELECT * FROM TBL_MAIL WHERE (USERID = 'apple' OR TARGETID = 'apple') AND IMPORTANT = '1' AND SENDER_DELETE = '0' ORDER BY MAILNUM DESC;

--휴지통
SELECT * FROM TBL_MAIL WHERE (USERID = 'apple' OR TARGETID = 'apple') AND SENDER_DELETE = '1' ORDER BY MAILNUM DESC;
